sudo: required

language: generic

services:
  - docker

script:
  - docker build -t gregoireweber/drupal8:latest drupal
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag gregoireweber/drupal8:latest gregoireweber/drupal8:"$TRAVIS_BUILD_NUMBER";
      docker push gregoireweber/drupal8:latest;
      docker push gregoireweber/drupal8:"$TRAVIS_BUILD_NUMBER";
    fi