version: '3.1'

services:

  drupal-php:
    build: ../drupal
    restart: unless-stopped
    volumes:
      - drupal-code:/var/www/html

  drupal-web:
    image: drupaldocker/nginx
    restart: unless-stopped
    environment:
      DOCROOT: /var/www/html
    ports:
      - 8080:80
    volumes:
      - drupal-code:/var/www/html:rw
    links:
      - drupal-php:php

  drupal-database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - drupal-database:/var/lib/mysql

volumes:
  drupal-database:
    driver: local
  drupal-code:
    driver: local